name: Deploy to S3

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::253041091599:role/github-project-aws
          aws-region: eu-north-1

      - name: Sync to S3
        run: aws s3 sync . s3://s3-cv-demo --exclude ".git/*" --exclude ".github/*"

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id E1SF7ERO1PIG8B --paths "/*"
